### ISSUE TITLE
Pipe jobs in

### ISSUE THREAD

**Issue by Bilge** [EdwinHoksberg/beanstalkd-cli#10]
Hi, there doesn't seem to be any way to pipe data in? Piping from a process, e.g. `varnishncsa | ./beanstalkd-cli_linux_amd64 put` seems to just buffer indefinitely instead of queueing jobs. How can I signal that each line should be treated as a job?

**Comment by Bilge** [comment]
I'll just use `xargs`.

**Comment by EdwinHoksberg** [comment]
I see that you already found a workaround, but I am interested in creating something for this issue because it does sound useful to me. Right now the `put` command reads until the EOF marker (which will only come when you close the process I think), but I'll try to change that so you can specify your own marker.

**Comment by Bilge** [comment]
I tried with `varnishncsa | sed 's/\n/\x4/' | ./beanstalkd-cli_linux_amd64 put` but it seems it is not sufficient to just send the EOF marker, the process has to actually disconnect. That is not very scriptable, except with `xargs` to continuously invoke the process, but that is probably not very efficient.
